/* This Jenkins File will be written to extensively deploy Kirloskar Theme Modules
    It will be written as a Declerative Pipeline
    
    ++++++++++++++++++++++++++++++++++++
    Author: Amitesh Anand
    Version: 1.0
    +++++++++++++++++++++++++++++++++++
*/

pipeline {
  agent any
  
  environment {
   
  
  

  inhondatheme_WORKSPACE ='C:/ProgramData/Jenkins/.jenkins/workspace/inhondatheme/iNFoundationLiferayWorkspace/themes'

 
  SONAR_PROJECTKEY = 'Shalby-Develop-IA'
  }
    
  // Define the Stages now 

    stages {
    
    stage('Compile') {
      steps {
      // Print out the Environment Variables to later dress up the most important onces
        bat 'echo "Printing the ENV variabes"'
        
        
         bat "C:/ProgramData/Jenkins/.jenkins/workspace/inhondatheme/iNFoundationLiferayWorkspace/themes/hondathemeupdated.bat"
         
         bat script:'''
          cd /d E:/hondatheme/poc/iNFoundationLiferayWorkspace/themes/in-control-panel-theme/
          echo %cd%
          C:/"Program Files"/nodejs/npm install gulp
          

          
         '''
         bat script:'''
         cd /d E:/hondatheme/poc/iNFoundationLiferayWorkspace/themes/in-control-panel-theme/
         C:/Users/amitesh.anand/AppData/Roaming/npm/gulp build
         '''
}

       

    
     
    



      
      }
    }

    }

 
    


          


     
                




              

              
                
    
       
     
     
    

    

        



      